### ISSUE TITLE
Rollup Error: 'router' is not exported by svelte-router/lib/svelte-router.js

### ISSUE THREAD

**Issue by BennyHinrichs** [spaceavocado/svelte-router-template#1]
Wondering if you can help with this Rollup error.

```javascript
node_modules/@spaceavocado/svelte-router/component/view.svelte:
'router' is not exported by node_modules/@spaceavocado/svelte-router/lib/svelte-router.js
```

Seems to have something to do with CommonJS exports, which I'm not incredibly familiar with.

Alright, so I did this in `view.svelte` and it seems to work:
```javascript
import Router from '@spaceavocado/svelte-router';
const {router} = Router;
```

Also had to do something similar in `view.svelte`:
```javascript
import Router from '@spaceavocado/svelte-router';
const {router, urlMatch, urlPrefix, trimPrefix} = Router;
```

And my `App.svelte`:
```javascript
import createRouter from '@spaceavocado/svelte-router';
const {ROUTER_MODE} = createRouter;
```

Seems like Rollup does not play well with named CommonJS exports. I'll see what I can find, but I'd love any suggestions.

Now what I think might be another Rollup-related issue: 
```javascript
Uncaught ReferenceError: process is not defined (tiny-warning-esm.js:1):
var isProduction = process.env.NODE_ENV === 'production';
```

**Comment by davidhorak** [comment]
Hi Benny,
The router is currently build as webpack UMD which not is not directly supported by Rollup. And this project template is set with Webpack. I will try to explore the options for Rollup.

**Comment by davidhorak** [comment]
@BennyHinrichs the [svelte-router](https://github.com/spaceavocado/svelte-router) has been updated to better support rollup. Please get the latest version of the [svelte-router-template](https://github.com/spaceavocado/svelte-router-template) or just the package [svelte-router](https://github.com/spaceavocado/svelte-router) itself, and follow this instruction: [Rollup Setup](https://github.com/spaceavocado/svelte-router#rollup-setup).

**Comment by BennyHinrichs** [comment]
Hey, you're awesome! Works like a charm :grin: I wanted to start with https://github.com/syonip/svelte-cordova, so this helps a ton.
